name: mweb_client
description: client library for interacting with a mwebd server
version: 0.1.0
repository: https://github.com/Cyrix126/mweb_client

environment:
  sdk: ^3.7.2

dependencies:
  grpc: ^4.0.1
  protobuf: ^4.0.0
  fixnum: ^1.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
